====== Publications ======
//<color green>---<ff Georgia><fs 100%>We need to spend less time reading research, and a bit more time thinking about what we are reading. </fs></ff>---</color>//


/*
===== Conference Papers under Review ===== 
 

Dr. Li is also associated with [[ISSACS|https://engineering.case.edu/research/institutes/smart-secure-connected-systems]] [[Schubert Center for Child Studies|https://schubert.case.edu]].



*/



===== Conference Papers =====
  - Tianxi Ji and **Pan Li**, "Less is More: Revisiting the Gaussian Mechanism for Differential Privacy," the the 33rd USENIX Security Symposium, Philadelphia, PA, August 14-16, 2024. (Acceptance rate: 98/515=19% for Summer'23)
  - Srinivasan Murali, Wenqiang Jin,  Vighnesh Sivaraman, Huadi Zhu, Tianxi Ji, **Pan Li**, and Ming Li, "Continuous Authentication Using Human-Induced Electric Potential," the Applied Computer Security Applications Conference (ACSAC), Austin, Texas, December 4-8, 2023 (Acceptance rate: 59/246=24%) 
  - Tianxi Ji, Erman Ayday, Emre Yilmaz, Ming Li, and **Pan Li**, "Privacy-Preserving Database Fingerprinting," the Network and Distributed System Security Symposium (NDSS), San Diego, California, February 27-March 3, 2023.
  - Tianxi Ji, Erman Ayday, Emre Yilmaz, and **Pan Li**, "Robust Fingerprinting of Genomic Databases," 30th Conference on Intelligent Systems for Molecular Biology (ISMB'22), July 10-14, 2022. (Acceptance Rate = 48/242 = 19.8%)
  - Emre Yilmaz, Tianxi Ji, Erman Ayday and **Pan Li**, "Genomic Data Sharing under Dependent Local Differential Privacy," ACM Conference on Data and Application Security and Privacy (CODASPY'21), Baltimore-Washington DC Area, April 24-26, 2022. 
  - Yifan Guo, Qianlong Wang, Tianxi Ji, Xufei Wang, **Pan Li**, "Resisting Distributed Backdoor Attacks in Federated Learning: A Dynamic Norm Clipping Approach," IEEE International Conference on Big Data (BigData'21), December 15-128 2021.
  - Tianxi Ji, Emre Yilmaz, Erman Ayday, and **Pan Li**, "The Curse of Correlations for Robust Fingerprinting of Relational Databases," The 24th International Symposium on Research in Attacks, Intrusions and Defenses (RAID'21), Donostia/San Sebastian, Spain, October 6-8, 2021. 
  - Yifan Guo, Lixing Yu, Qianlong Wang, Tianxi Ji, Yuguang Fang, Jin Wei-Kocsis, and **Pan Li**, "Weak Signal Detection in 5G+ Systems: A Distributed Deep Learning Framework," the Twenty-Second ACM International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing (MobiHoc'21), Shanghai, China, July 26-29, 2021.
  - Tianxi Ji, **Pan Li**, Emre Yilmaz, Erman Ayday, Yanfang (Fanny) Ye, Jinyuan Sun, "Differentially Private Binary- and Matrix-Valued Data Query: An XOR Mechanism," 47th International Conference on Very Large Data Bases (VLDB'21), Copenhagen, Denmark, August 16-20, 2021.
  - Emre Yilmaz, Erman Ayday, Tianxi Ji, and **Pan Li**, "Preserving Genomic Privacy via Selective Sharing," ACM Workshop on Privacy in the Electronic Society (WPES), November 9, 2020. 
  - Yiming Zhang, Yujie Fan, Shifu Hou, Yanfang Ye, Xusheng Xiao, **Pan Li**, Chuan Shi, Liang Zhao, and Shouhuai Xu, "Cyber-guided Deep Neural Network for Malicious Repository Detection in GitHub," IEEE International Conference on Knowledge Graph (ICKG'20), Nanjing, China, August 9-11, 2020.
  - Kun Yang, Xuhui Chen, and **Pan Li**, "Data Streaming Analysis Framework for Through-time 3D Free-breathing Liver DCE-MRI," IEEE International Conference on Big Data (BigData'19), Los Angeles, CA, December 9-12, 2019.
  - Tianxi Ji, Changqing Luo, Yifan Guo, Qianlong Wang, and **Pan Li**, "Differentially Private Community Detection in Attributed Social Networks," the 11th Asian Conference on Machine Learning (ACML'19), Nagoya, Japan, November 17-19, 2019. 
  - Yifan Guo, Tianxi Ji, Qianlong Wang, Lixing Yu, and **Pan Li**, "Quantized Adversarial Training: An Iterative Quantized Local Search Approach," the 18th IEEE International Conference on Data Mining (ICDM'19), Beijing, China, November 8-11, 2019. (Acceptance Ratio: 18.5% with 95 regular and 99 short papers)
  - Xinyue Zhang, Jiahao Ding, Sai Mounika Errapotu, Xiaoxia Huang, **Pan Li**, and Miao Pan, "Differentially Private Functional Mechanism for Generative Adversarial Networks," IEEE Global Communications Conference (GLOBECOM'19), Waikoloa, Hawaii, December 9-13, 2019.
  - Feng Hu, Bing Chen, Jingyi Wang, Ming Li, **Pan Li**, and Miao Pan, "MastDP: Matching Based Double Auction Mechanism for Spectrum Trading with Differential Privacy," IEEE Global Communications Conference (GLOBECOM'19), Waikoloa, Hawaii, December 9-13, 2019.
  - Lixing Yu, Wenqiang Jin, Ming Li, and **Pan Li**, "Exploring Spatial-Temporal Patterns from Individual User Cellular Traffic," IEEE International Symposium on Dynamic Spectrum Access Networks, Newark, NJ, November 11-14, 2019.
  - Jinlong Ji, Xuhui Chen, QianlongWang, Lixing Yu, and Pan Li, "Learning to Learn Gradient Aggregation by Gradient Descent," the 28th International Joint Conference on Artificial Intelligence (IJCAI'19), Macao, China, August 10-16 2019. (Acceptance Ratio = 850/4752 = 17.9%)
  - Dian Shi, Xuanheng Li, Ming Li, Jie Wang, **Pan Li**, and Miao Pan, "Optimal Transportation Network Company Vehicle Dispatching via Deep Deterministic Policy Gradient," the 14th International Conference on Wireless Algorithms, Systems, and Applications (WASA), Hawaii, June 24-26, 2019.
  - Mingyan Xiao, Ming Li, Linke Guo, Miao Pan, Zhu Han, and **Pan Li**, "Securing Task Allocation in Mobile Crowd Sensing: An Incentive Design Approach," IEEE Conference on Communications and Network Security (CNS'19), Washington, D.C., June 10-12, 2019.
  - Xufei Wang, Weixian Liao, Yifan Guo, Lixing Yu, Qianlong Wang, Miao Pan, and **Pan Li**, "PerRNN: Personalized Recurrent Neural Networks for Acceleration-based Human Activity Recognition," IEEE International Conference on Communications (ICC’19), Shanghai, China, May 20-24, 2019.
  - Xuhui Chen, Jinlong Ji, Changqing Luo, Weixian Liao, and **Pan Li**, "When Machine Learning Meets Blockchain: A Decentralized, Privacy-preserving, and Secure Design," IEEE International Conference on Big Data (BigData'18), Seattle, WA, December 10-13, 2018. (Acceptance Ratio = 98 (regular papers)/518 = 18.9%)
  - Weixian Liao, Yifan Guo, Xuhui Chen, and **Pan Li**, "A Unified Unsupervised Gaussian Mixture Variational Autoencoder for High Dimensional Outlier Detection," IEEE International Conference on Big Data (BigData'18), Seattle, WA, December 10-13, 2018. (Acceptance Ratio = 98 (regular papers)/518 = 18.9%) 
  - Jinlong Ji, Xuhui Chen, Lixing Yu, Changqing Luo, and **Pan Li**, "SecureNets: Secure Inference of Deep Neural Networks on an Untrusted Cloud," the 10th Asian Conference on Machine Learning (ACML'18), Beijing, China, November 14-16, 2018. (Acceptance Ratio = 57/230 = 24.8%)
  - Yifan Guo, Weixian Liao, Qianlong Wang, Lixing Yu, Tianxi Ji, and **Pan Li**, "Multidimensional Time Series Anomaly Detection: A GRU-based Gaussian Mixture Variational Autoencoder Approach," the 10th Asian Conference on Machine Learning (ACML'18), Beijing, China, November 14-16, 2018. (Acceptance Ratio = 57/230 = 24.8%)
  - Sergio Salinas, Ming Li, and **Pan Li**, "Energy-based Detection of Defect Injection Attacks in IoT-enabled Manufacturing," IEEE Global Communications Conference (GLOBECOM'18), Abu Dhabi, UAE, December 9-13, 2018. 
  - Xinyue Zhang, Jingyi Wang, Hongning Li, Yuanxiong Guo, Qingqi Pei, **Pan Li**, and Miao Pan, "Data-Driven Caching with Users' Local Differential Privacy in Information-Centric Networks," IEEE Global Communications Conference (GLOBECOM'18), Abu Dhabi, UAE, December 9-13, 2018. 
  - Changqing Luo, Sergio Salinas, and **Pan Li**, "Efficient Privacy-Preserving Large-scale CP Tensor Decompositions," IEEE Global Communications Conference (GLOBECOM'18), Abu Dhabi, UAE, December 9-13, 2018. 
  - Xuhui Chen, Jinlong Ji, Tianxi Ji, and **Pan Li**, "Cost-Sensitive Deep Active Learning for Epileptic Seizure Detection," the 9th ACM Conference on Bioinformatics, Computational Biology, and Health Informatics (BCB'18), Washington, DC, August 29-September 1, 2018.
  - Jinlong Ji, Changqing Luo, Xuhui Chen, Lixing Yu, and **Pan Li**, "{{pakdd18.pdf|Cross-Domain Sentiment Classification via A Bifurcation-LSTM}}," the 22nd Pacific-Asia Conference on Knowledge Discovery and Data Mining (PAKDD'18), June 3-6, 2018. (Acceptance Ratio = 59 (long papers)/590 = 10%, **Best Application Award**)
  - Jinlong Ji, Xuhui Chen, Changqing Luo, and **Pan Li**, "{{bhi18.pdf|A Deep Multi-task Learning Approach for ECG Data Analysis}}," IEEE Conference on Biomedical and Health Informatics (BHI'18), Las Vegas, NV, March 4-7, 2018.
  - Changqing Luo, Jinlong Ji, Qianlong Wang, Lixing Yu, and **Pan Li**, "{{icc18-nlos.pdf|Online Power Control for 5G Wireless Communications: A Deep Q-network Approach}}," IEEE International Conference on Communications (ICC'18), Kansas City, MO, May 20-24, 2018.
  - Kaijin Zhang, Changqing Luo, and **Pan Li**, "{{icc18-matrix.pdf|Secure outsourcing of Matrix convolutions}}," IEEE International Conference on Communications (ICC'18), Kansas City, MO, May 20-24, 2018.
  - Changqing Luo, Sergio Salinas, Ming Li, and **Pan Li**, "{{dasc17.pdf|Energy-efficient Computation Automatic Offloading in Mobile Edge Computing}}," the 15th IEEE International Conference on Dependable, Autonomic and Secure Computing (DASC'17), Orlando, FL, November 6-10, 2017 (**Best Paper Award**)
  - Jiajun Xin, Ming Li, Linke Guo, and **Pan Li**, "{{cns.pdf|Practical Privacy-Preserving Spectrum Query Schemes for Database-Driven CRNs with Multiple Service Providers}}," IEEE Conferences on Communications and Network Security (CNS'17), Las Vegas, NV, October 9-11, 2017. 
  - Sergio Salinas and **Pan Li**, "{{bcb17.pdf|Secure Cloud Computing for Pairwise Sequence Alignment}}," the 8th ACM Conference on Bioinformatics, Computational Biology, and Health Informatics (BCB'17), Boston, MA, August 20-23, 2017.
  - Changqing Luo, Kaijin Zhang, Sergio Salinas, and **Pan Li**, "{{bigdatase17.pdf|Efficient Privacy-preserving Outsourcing of Large-scale QR Factorization}}," the 11th IEEE International Conference On Big Data Science And Engineering(BigDataSE'17), Sydney, Australia, August 1-4, 2017.
  - Lixing Yu, Qianlong Wang, Yifan Guo, and **Pan Li**, "{{ccaa17.pdf|Spectrum Availability Prediction for Cognitive Aerospace Communications: A Deep Learning Perspective}}," IEEE Cognitive Communications for Aerospace Applications Workshop, Cleveland, OH, June 27-28, 2017.
  - Xuhui Chen, Jinlong Ji, Kenneth A. Loparo, and **Pan Li**, "{{bhi17.pdf|Real-time Personalized Cardiac Arrhythmia Detection and Diagnosis: A Cloud Computing Architecture}}," IEEE Conference on Biomedical and Health Informatics (BHI'17), Orlando, FL, February 16-19, 2017.  
  - W. Liao, W. Du, S. Salinas, and **P. Li**, "{{smartcity16.pdf|Efficient Privacy-preserving Outsourcing of Large-scale Convex Separable Programming for Smart Cities}}," the 14th IEEE International Conference on Smart City (SmartCity'16), Sydney, Australia, December 12-14, 2016.
  - Jiajun Xin, Ming Li, Changqing Luo, and **Pan Li**, "{{globecom16.pdf|Privacy-Preserving Spectrum Query with Location Proofs in Database-Driven CRNs}}," IEEE Global Communications Conference (Globecom'16), Washington, DC, December 4-8, 2016.
  - Sergio Salinas, Changqing Luo, Weixian Liao, and **Pan Li**, "{{asiaccs16-qp.pdf|Efficient Secure Outsourcing of Large-scale Quadratic Programs}}," the ACM Asia Conference on Computer and Communications Security (ASIACCS'16), Xi'an, China, May 30 - June 3, 2016. (Acceptance Ratio = 73/350 = 20.9%). (We have corrected a technical issue in the paper. Here is the {{asiaccs16updated.pdf|updated version}}.)
  - Gaoqiang Zhuo, Qi Jia, Linke Guo, Ming Li, and **Pan Li**, "{{infocom16.pdf|Privacy-preserving Verifiable Data Aggregation and Analysis for Cloud-assisted Mobile Crowdsourcing}}," IEEE International Conference on Computer Communication (INFOCOM'16), San Francisco, California, April 10-15, 2016. (Acceptance Ratio = 300/1644 = 18.25%)
  - Yue Tong, Jinyuan Sun, Kai Sun, and **Pan Li**, "{{globecom15.pdf|Outsourcing Power System Simulations}}," IEEE Global Communications Conference (Globecom'15), San Diego, CA, December 6-10, 2015.
  - Yingyuan Yang, Jinyuan Sun, and **Pan Li**, "{{mass15.pdf|Model Retraining and Dynamic Privilege-based Access Control for Implicit Authentication Systems}}," IEEE International Conference on Mobile Ad Hoc and Sensor Systems (MASS'15), Dallas, TX, October 19-22, 2015.
  - Linke Guo, Yuguang Fang, Ming Li, and **Pan Li**, "{{infocom15-mhealth.pdf|Verifiable Privacy-preserving Monitoring for Cloud-assisted mHealth Systems}}," IEEE International Conference on Computer Communications (INFOCOM'15), Hong Kong, China, April 26-May 1, 2015. (Acceptance ratio = 316/1640 = 19%)
  - Ming Li, **Pan Li**, Linke Guo, and Xiaoxia Huang, "{{infocom15-pper.pdf|PPER: Privacy-Preserving Economic-Robust Spectrum Auction in Wireless Networks}}," IEEE International Conference on Computer Communications (INFOCOM'15), Hong Kong, China, April 26-May 1, 2015. (Acceptance ratio = 316/1640 = 19%)
  - Sergio Salinas, Changqing Luo, Xuhui Chen, and **Pan Li**, "{{infocom15-lse.pdf|Efficient Secure Outsourcing of Large-scale Linear Systems of Equations}}," IEEE International Conference on Computer Communications (INFOCOM'15), Hong Kong, China, April 26-May 1, 2015. (Acceptance ratio = 316/1640 = 19%)
  - Yawei Pang, Yanru Zhang, Yunan Gu, Miao Pan, Zhu Han, and **Pan Li**, "{{globecom14.pdf|Efficient Data Collection for Wireless Rechargeable Sensor Clusters in Harsh Terrains Using UAVs}}," IEEE Global Communications Conference (GLOBECOM'14), Austin, TX, December 8-12, 2014.
  - Sergio Salinas, Changqing Luo, Weixian Liao, **Pan Li**, "{{chinacom14.pdf|State Estimation for Energy Theft Detection in Microgrids}}," the 9th International Conference on Communications and Networking in China (ChinaCom'14), Maoming, China, August 14-16, 2014. (**Best Paper Award**)
  - Weixian Liao, Ming Li, Sergio Salinas, **Pan Li**, and Miao Pan, "{{icdcs14.pdf|Optimal Energy Cost for Strongly Stable Multi-hop Green Cellular Networks}}," IEEE International Conference on Distributed Computing Systems (ICDCS'14), Madrid, Spain, June 30-July 3, 2014. (Acceptance ratio: 66/500 = 13%)
  - Yue Tong, Jinyuan Sun, Sherman S. M. Chow, and **Pan Li**, "{{spcc13.pdf|Towards Auditable Cloud-Assisted Access of Encrypted Health Data}}," the 4th International Workshop on Security and Privacy in Cloud Computing, Maryland, USA, October 14-16, 2013.
  - Yan Long, Hongyan Li, Miao Pan, **Pan Li**, and Jiandong Li, "{{iccc13.pdf|Scalable Video Coding Based Video Transmission in MRMC Networks: A Cross-Layer Design Perspective}},"  IEEE International Conference on Communications in China (ICCC'13), Xi'an, China, August 12-14, 2013.
  - Ming Li, **Pan Li**, Miao Pan, and Jinyuan Sun, "{{infocom13-auction.pdf|Economic-Robust Transmission Opportunity Auction in Multi-hop Wireless Networks}}," IEEE International Conference on Computer Communications (INFOCOM'13), Turin, Italy, April 14-19, 2013. (Acceptance ratio: 280/1613 = 17%)
  - Ming Li, Sergio Salinas, Arun Thapa, and **Pan Li**, "{{infocom13-ncd.pdf|n-CD: A Geometric Approach to Preserving Location Privacy in Location-Based Services}}," IEEE International Conference on Computer Communications (INFOCOM'13), Turin, Italy, April 14-19, 2013. (Acceptance ratio: 280/1613 = 17%)
  - Miao Pan, Hao Yue, **Pan Li** and Yuguang Fang, "{{iccc-coop.pdf|Throughput Maximization of Cooperative Wireless Mesh Networks Using Directional Antennas}}," IEEE International Conference on Communications in China (ICCC'12), Beijing, China, August 15-18, 2012.
  - Sergio Salinas, Ming Li, **Pan Li**, "{{secon12.pdf|Privacy-Preserving Energy Theft Detection in Smart Grids}}," IEEE Communications Society Conference on Sensor, Mesh and Ad Hoc Communications and Networks (SECON'12), Seoul, Korea, June 18-21, 2012. 
  - Dianjie Lu, Xiaoxia Huang, **Pan Li**, Jianping Fan, "{{infocom12-conn.pdf|Connectivity of Large-Scale Cognitive Radio Ad Hoc Networks}}," IEEE International Conference on Computer Communications (INFOCOM'12), Orlando, Florida, March 25-30, 2012. (Acceptance ratio: 278/1547 = 18%)
  - Miao Pan, **Pan Li**, Yang Song, Yuguang Fang, and Phone Lin, "{{infocom12-sc.pdf|Spectrum Clouds: A Session Based Spectrum Trading System for Multi-hop Cognitive Radio Networks}}," IEEE International Conference on Computer Communications (INFOCOM'12), Orlando, Florida, March 25-30, 2012. (Acceptance ratio: 278/1547 = 18%)
  - Miao Pan, Hongyan Li, **Pan Li**, and Yuguang Fang, "{{globecom11-auction.pdf|Dealing with the Untrustworthy Auctioneer in Combinatorial Spectrum Auction}}," IEEE Global Communications Conference (GLOBECOM'11), Houston, TX, December 5-9, 2011.
  - Kui Liu, Yang Cheng, **Pan Li**, and Tarunraj Singh, "{{globecom11.pdf|Source Localization on Two-Dimensional Grid}}," IEEE Global Communications Conference (GLOBECOM'11), Houston, TX, December 5-9, 2011.
  - Xiaoxia Huang, Dianjie Lu, **Pan Li**, and Yuguang Fang, "{{icdcs11.pdf|Coolest Path: Spectrum Mobility Aware Routing Metrics in Cognitive Ad Hoc Networks}}," IEEE International Conference on Distributed Computing Systems (ICDCS'11), Minneapolis, MN, June 20-24, 2011. (Acceptance ratio: 87/565 = 15.4%)
  - **Pan Li**, Xiaoxia Huang, and Yuguang Fang, "{{infocom11-cellular.pdf|Capacity Scaling of Multihop Cellular Networks}}，" IEEE International Conference on Computer Communications (INFOCOM'11), Shanghai, China, April 10-15, 2011. (Acceptance ratio: 291/1823 = 15.96%)
  - **Pan Li**, Miao Pan, and Yuguang Fang, "{{infocom11-3d.pdf|The Capacity of Three-Dimensional Wireless Ad Hoc Networks}}," IEEE International Conference on Computer Communications (INFOCOM'11), Shanghai, China, April 10-15, 2011. (Acceptance ratio: 291/182 3= 15.96%)
  - Miao Pan, Chi Zhang, **Pan Li**, and Yuguang Fang, "{{infocom11-cognitive.pdf|Joint Routing and Link Scheduling for Cognitive Radio Networks under Uncertain Spectrum Supply}}," IEEE International Conference on Computer Communications (INFOCOM'11), Shanghai, China, April 10-15, 2011. (Acceptance ratio: 291/1823 = 15.96%)
  - Miao Pan, Yang Song, **Pan Li**, and Yuguang Fang, "{{globecom10.pdf|Reward and Risk for Opportunistic Spectrum Accessing in Cognitive Radio Networks}}," IEEE Global Communications Conference (GLOBECOM'10), Miami, FL, December 6-10, 2010.
  - Ren Han, Xiaoxia Huang, and **Pan Li**, "{{qshine10.pdf|Transport Control Based on Spectrum Switching Detection in Cognitive Radio Ad Hoc Networks}}," the seventh International ICST Conference on Heterogeneous Networking for Quality, Reliability, Security and Robustness (QShine'10), Houston, TX, November 17-19, 2010. (Invited Paper) 
  - **Pan Li** and Yuguang Fang, "{{infocom10-hetero.pdf|The Capacity of Heterogeneous Wireless Networks}}," IEEE International Conference on Computer Communications (INFOCOM’10), San Diego, CA, March 15-19, 2010. (There were some typos in the conference paper, which have been corrected in {{infocom10-h-updated.pdf|this version}}.) (Acceptance ratio: 276/1575 = 17.5%)
  - **Pan Li**, Yuguang Fang, and Jie Li, “{{infocom10-mobility.pdf|Throughput, Delay, and Mobility in Wireless Ad Hoc Networks}},” IEEE International Conference on Computer Communications (INFOCOM’10), San Diego, CA, March 15-19, 2010. (There were some typos in the conference paper, which have been corrected in {{infocom10-m-updated.pdf|this version}}.) (Acceptance ratio: 276/1575 = 17.5%)
  - Hao Wen, Jia Liu, Chuang Lin, Fengyuan Ren, **Pan Li**, and Yuguang Fang, "{{mswim09.pdf|RENA: Region-based Routing in Intermittently Connected Mobile Network}}," ACM International Conference on Modeling, Analysis and Simulation of Wireless and Mobile Systems (MSWiM'09), Tenerife, Canary Islands, Spain, October 26-30, 2009. (**A Best Paper Award Candidate**)  
  - **Pan Li** and Yuguang Fang, "{{milcom08.pdf|Saturation Throughput of IEEE 802.11 DCF in Multi-hop Ad Hoc Networks}}," IEEE Military Communications Conference (Milcom'08), San Diego, CA, November 17-19, 2008.
  - Chi Zhang, **Pan Li**, Yuguang Fang, and Pramod P. Khargonekar, "{{icdcs08.pdf|Decentralized Routing in Nonhomogeneous Poisson Networks}}," IEEE International Conference on Distributed Computing Systems (ICDCS'08), Beijing, China, June 17-20, 2008. (Acceptance ratio: 102/638 = 16.0%)
  - Qiang Shen, Xuming Fang, Rongsheng Huang, **Pan Li** and Yuguang Fang, "{{qshine08.pdf|Leveraging Spatial Reuse with Adaptive Carrier Sensing in 802.11 Wireless Networks}}," the Fifth International ICST Conference on Heterogeneous Networking for Quality, Reliability, Security and Robustness (QShine'08), HongKong, China, July 28-31, 2008.
  - Qiang Shen, Xuming Fang, **Pan Li** and Yuguang Fang, "{{icc08.pdf|Admission Control for Providing QoS in Wireless Mesh Networks}}," IEEE International Conference on Communications (ICC'08), Beijing, China, May 19-23, 2008.
  - **Pan Li**, Nicola Scalabrino, Yuguang Fang, E. Gregori, and Imrich Chlamtac, "{{globecom07.pdf|Channel Interference in IEEE 802.11b Systems}}," IEEE Global Communications Conference (GLOBECOM'07), Washington, D.C., November 26-30, 2007.
  - Roberto Riggio, Francesco De Pellegrini, Nicola Scalabrino, **Pan Li**, Yuguang Fang, and Imrich Chlamtac, "{{milcom07.pdf|Performance of a Novel Adaptive Traffic Aggregation Scheme for Wireless Mesh Networks}}," IEEE Military Communications Conference (Milcom'07), Orlando, FL, October 29-31, 2007.
  - **Pan Li**, Chi Zhang, and Yuguang Fang, "{{icdcs07.pdf|Asymptotic Connectivity in Wireless Networks Using Directional Antennas}}," IEEE International Conference on Distributed Computing Systems (ICDCS'07), Toronto, Canada, June 25-29, 2007. (Acceptance ratio: 71/528 = 13.4%)
  - **Pan Li**, Hongqiang Zhai, and Yuguang Fang, "{{milcom06.pdf|A Directional MAC Protocol for Ad Hoc Networks}}," IEEE Military Communications Conference (Milcom'06), Washington, D.C., October 23-25, 2006.










===== Journal Papers =====
  - Tianxi Ji , Erman Ayday, Emre Yilmaz, **Pan Li**, "Towards Robust Fingerprinting of Relational Databases by Mitigating Correlation Attacks," to appear in //IEEE Transactions on Dependable and Secure Computing//, 2022.
  - Tianxi Ji, Changqing Luo, Lixing Yu, Qianlong Wang, Siheng Chen, Arun Thapa, and **Pan Li**, “Energy-Efficient Computation Offloading in Mobile Edge Computing Systems with Uncertainties,” to appear in //IEEE Transactions on Wireless Communications//, 2021.
  - Q. Wang, Y. Guo, T. Ji, X. Wang, B. Hu, and **P. Li**,"Towards Combatting COVID-19: A Risk Assessment System", to appear in //IEEE Internet of Things Journal//, 2021.
  - Qianlong Wang, Yifan Guo, Lixing Yu, Xuhui Chen, and **Pan Li**, "Deep Q-Network-Based Feature Selection for Multisourced Data Cleaning," to appear in //IEEE Internet of Things Journal//, 2021.
  - Mingyan Xiao, Wenqiang Jin, Ming Li, Lei Yang, Arun Thapa, and **Pan Li**, "Collusion-Resistant Worker Recruitment in Crowdsourcing Systems," to appear in // IEEE Transactions on Mobile Computing//, 2021.
  - Xinyue Zhang, Hongning Li, Jingyi Wang, Yuanxiong Guo, Qingqi Pei, **Pan Li**, and Miao Pan, "Data-Driven Caching with Users’ Content Preference Privacy in Information-Centric Networks," //IEEE Transactions on Wireless Communications//, Vol. 20, No. 9, pp. 5744-5753, April 2021.
  - Lixing Yu, Ming Li, Wenqiang Jin, Yifan Guo, Qianlong Wang, Feng Yan, and **Pan Li**, "STEP: A Spatio-Temporal Fine-Granular User Traffic Prediction System for Cellular Networks," // IEEE Transactions on Mobile Computing//, Vol. 20, No. 12, pp. 3453-3466, June 2020.
  - Yifan Guo, Tianxi Ji, Qianlong Wang, Lixing Yu, Geyong Min, and **Pan Li**, "Unsupervised Anomaly Detection in IoT Systems for Smart Cities," //IEEE Transactions on Network Science and Engineering//, Vol. 7, No. 4, pp. 2231-2242, October-December 2020. 
  - Qianlong Wang, Yifan Guo, Xufei Wang, Tianxi Ji, Lixing Yu, and **Pan Li**, "AI at the Edge: Blockchain-Empowered Secure Multiparty Learning with Heterogeneous Models," //IEEE Internet of Things Journal//, Vol. 7, No. 10, pp. 9600-9610, October 2020.
  - Lixing Yu, Yifan Guo, Qianlong Wang, Changqing Luo, Ming Li, Weixian Liao, and **Pan Li**, "Spectrum Availability Prediction for Cognitive Radio Communications: A DCG Approach," //IEEE Transactions on Cognitive Communications and Networking//, Vol. 6, No. 2, pp. 476-485, June 2020.
  - Qianlong Wang, Tianxi Ji, Yifan Guo, Lixing Yu, Xuhui Chen, and **Pan Li**, "TrafficChain: A Blockchain based Secure and Privacy-Preserving Traffic Map," //IEEE Access//, Vol. 8, pp. 60598-60612, March 2020.
  - Changqing Luo, Jinlong Ji, Qianlong Wang, Xuhui Chen, and **Pan Li**, "Channel State Information Prediction in 5G Wireless Communications: A Deep Learning Approach," //IEEE Transactions on Network Science and Engineering//, Vol. 7, No. 1, pp. 227-236, January-March 2020.
  - Tianxi Ji, Changqing Luo, Yifan Guo, Qianlong Wang, Lixing Yu, and **Pan Li**, "Community Detection in Online Social Networks: A Differentially Private and Parsimonious Approach," //IEEE Transactions on Computational Social Systems//, Vol. 7, No. 1, pp. 151-163, February 2020.
  - Changqing Luo, Kaijin Zhang, Sergio Salinas, and **Pan Li**, "SecFact: Secure Large-scale QR and LU Factorizations," to appear in //IEEE Transactions on Big Data//.
  - Changqing Luo, Jinlong Ji, Xuhui Chen, Ming Li, Lawrence T. Yang, and **Pan Li**, "Parallel Secure Outsourcing of Large-scale Nonlinearly Constrained Nonlinear Programming Problems," to appear in //IEEE Transactions on Big Data//.
  - Weixian Liao, Changqing Luo, Sergio Salinas, and **Pan Li**, "Efficient Secure Outsourcing of Large-scale Convex Separable Programming for Big Data," //IEEE Transactions on Big Data//, Vol. 5, No. 3, 368-378, September 2019.
  - Ming Li, Weixian Liao, Xuhui Chen, Jinyuan Sun, Xiaoxia Huang, and **Pan Li**, "{{tmc0818.pdf|Economic-Robust Transmission Opportunity Auction for D2D Communications in Cognitive Mesh Assisted Cellular Networks}}," //IEEE Transactions on Mobile Computing//, Vol. 17, No. 8, pp. 1806-1819, August 2018.
  - Sergio Salinas, Changqing Luo, Xuhui Chen, Weixian Liao, and **Pan Li**, "{{tbd0118.pdf|Efficient Secure Outsourcing of Large-scale Sparse Linear Systems of Equations}}," //IEEE Transactions on Big Data//, Vol. 4, No. 1, pp. 26-39, January-March 2018.
  - Weixian Liao, Sergio Salinas, Ming Li, **Pan Li**, Kenneth A. Loparo, "{{iot1217.pdf|Cascading Failure Attacks in the Power System: A Stochastic Game Perspective}}," //IEEE Internet of Things Journal//, Vol. 4, No. 6, pp. 2247-2259, December 2017.
  - Qianlong Wang, Yifan Guo, Lixing Yu, and **Pan Li**, "{{tetc0417.pdf|Earthquake Prediction based on Spatio-Temporal Data Mining: An LSTM Network Approach}}," //IEEE Transactions on Emerging Topics in Computing//, 2017. 
  - Sheng Cai, Weixian Liao, Changqing Luo, Ming Li, Xiaoxia Huang, and **Pan Li**, "{{tvt0517.pdf|CRIL: An Efficient Online Adaptive Indoor Localization System}}," //IEEE Transactions on Vehicular Technology//, Vol. 66, No. 5, 4148-4160, May 2017.
  - Gaoqiang Zhuo, Qi Jia, Linke Guo, Ming Li, and **Pan Li**, "{{iot0417.pdf|Privacy-preserving Verifiable Set Operation in Big Data for Cloud-assisted Mobile Crowdsourcing}}," //IEEE Internet of Things Journal//, Vol. 4, No. 2, pp. 572-582, April 2017.
  - Weixian Liao, Ming Li, Sergio Salinas, **Pan Li**, and Miao Pan, "{{tetc1216.pdf|Energy-Source-Aware Cost Optimization for Green Cellular Networks with Strong Stability}}," //IEEE Transactions on Emerging Topics in Computing//, Vol. 4, No. 4, pp. 541-555,  October-December, 2016.
  - Arun Thapa, Weixian Liao, Ming Li, **Pan Li**, and Jinyuan Sun, "{{tpds0816.pdf|SPA: A Secure and Private Auction Framework for Decentralized Online Social Networks}}," //IEEE Transactions on Parallel and Distributed Systems//, Vol. 27, No. 8, 2394-2407, August 2016. (Supplemental materials can be found {{tpds0816appen.pdf|here}}.)
  - Sergio Salinas and **Pan Li**, "{{tps0316.pdf|Privacy-Preserving Energy Theft Detection in Microgrids: A State Estimation Approach}}," //IEEE Transactions on Power Systems//, Vol. 31, No. 2, pp. 883-894, March 2016.
  - Maria Kangas, Savo Glisic, Yuguang Fang, and **Pan Li**, "{{tccn0915.pdf|Resource Harvesting in Cognitive Wireless Computing Networks With Mobile Clouds and Virtualized Distributed Data Centers: Performance Limits}}," //IEEE Transactions on Cognitive Communications and Networking//, Vol. 1, No. 3, pp. 318-334, September 2015.
  - Arun Thapa, Ming Li, Sergio Salinas, and **Pan Li**, "{{tpds0615.pdf|Asymmetric Social Proximity Based Private Matching Protocols for Online Social Networks}}," //IEEE Transaction on Parallel and Distributed System//, Vol. 26, No. 6, pp. 1547-1559, June 2015.
  - Ming Li, Sergio, Salinas, **Pan Li**, Jinyuan Sun, and Xiaoxia Huang, "{{tmc0615.pdf|MAC-Layer Selfish Misbehavior in IEEE 802.11 Ad Hoc Networks: Detection and Defense}}," //IEEE Transactions on Mobile Computing//, Vol. 14, No. 6, pp. 1203-1217, June 2015. 
  - Ming Li, **Pan Li**, Xiaoxia Huang, Yuguang Fang, and Savo Glisic, "{{tmc0215.pdf|Energy Consumption Optimization for Multihop Cognitive Cellular Networks}}," //IEEE Transactions on Mobile Computing//, Vol. 4, No. 2, pp. 358-372, February 2015. (//Feature Article of the February Issue//). 
  - Ming Li, Sergio Salinas, **Pan Li**, Xiaoxia Huang, Yuguang Fang, and Savo Glisic, "{{tmc0115.pdf|Optimal Scheduling for Multi-radio Multi-channel Multi-hop Cognitive Cellular Networks}}," //IEEE Transactions on Mobile Computing//, Vol. 14, No. 1, pp. 139-154, January 2015.
  - Miao Pan, **Pan Li**, Yang Song, Yuguang Fang, Phone Lin, and Savo Glisic, "{{jsac0314.pdf|When Spectrum Meets Clouds: Optimal Session Based Spectrum Trading under Spectrum Uncertainty}}," //IEEE Journal on Selected Areas in Communications -- Cognitive Radio Series//, Vol. 32, No. 3, pp. 615-627, March 2014.
  - Yue Tong, Jinyuan Sun, Sherman S. M. Chow, and **Pan Li**, "{{jbhi0314.pdf|Cloud-assisted Mobile-access of Health Data with Privacy and Auditability}}," //IEEE Journal of Biomedical and Health Informatics//, Vol. 18, No. 2, pp. 419-429, March 2014.
  - Ming Li, Sergio Salinas, and **Pan Li**, "{{tpds0214.pdf|Locaward: A Security and Privacy Aware Location-Based Rewarding System}}," //IEEE Transactions on Parallel and Distributed Systems -- Special Issue on Trust, Security, and Privacy//, Vol. 25, No. 2, pp. 343-352, February 2014.
  - Ming Li and **Pan Li**, "{{tetc1213.pdf|Crowdsourcing in Cyber-Physical Systems: Stochastic Optimization with Strong Stability}}," //IEEE Transactions on Emerging Topics in Computing -- Special Issue on Cyber-Physical Systems//, Vol. 1, No. 2, pp. 218-231, December 2013.
  - Sergio Salinas, Ming Li, **Pan Li**, and Yong Fu, "{{tsg1213.pdf|Dynamic Energy Management for the Smart Grid with Distributed Energy Resources}}," //IEEE Transactions on Smart Grid//, Vol. 4, No. 4, pp. 2139-2151, December 2013.
  - Sergio Salinas, Ming Li, and **Pan Li**, "{{jsac0913.pdf|Privacy-Preserving Energy Theft Detection in Smart Grids: A P2P Computing Approach}}," //IEEE Journal on Selected Areas in Communications -- Special Issue on Emerging Technologies in Communications//, Vol. 31, No. 9, pp. 257-267, September 2013.
  - Sergio Salinas, Ming Li, and **Pan Li**, "{{tsg0313.pdf|Multi-Objective Optimal Energy Consumption Scheduling in Smart Grids}}," //IEEE Transactions on Smart Grid//, Vol. 4, No. 1, pp. 341-348, March 2013.
  - **Pan Li** and Yuguang Fang, "{{tmc1212.pdf|On the Throughput Capacity of Heterogeneous Wireless Networks}}," //IEEE Transactions on Mobile Computing//, Vol. 11, No. 12, pp. 2073-2086, December 2012.
  - **Pan Li**, Miao Pan, and Yuguang Fang, "{{ton0812.pdf|Capacity Bounds of Three-Dimensional Wireless Ad Hoc Networks}}," //IEEE Transactions on Networking//, Vol. 20, No. 4, pp. 1304-1315, August 2012.
  - Miao Pan, **Pan Li**, and Yuguang Fang, "{{jsac0512.pdf|Cooperative Communication Aware Link Scheduling for Cognitive Vehicular Ad-hoc Networks}}," //IEEE Journal on Selected Areas in Communications -- Special Issue on Broadband Wireless Communications for High Speed Vehicles//, Vol. 30, No. 4, pp. 760-768, May 2012.
  - **Pan Li**, Yuguang Fang, Jie Li, and Xiaoxia Huang, "{{tmc-mobility12.pdf|Smooth Trade-offs Between Throughput and Delay in Mobile Ad Hoc Networks}}," //IEEE Transactions on Mobile Computing//, Vol. 11, No. 3, pp. 427-438, March 2012.
  - Miao Pan, Chi Zhang, **Pan Li**, and Yuguang Fang, "{{jsac0212.pdf|Spectrum Harvesting and Sharing in Multi-hop CRNs under Uncertain Spectrum Supply}}," //IEEE Journal on Selected Areas in Communications -- Special Issue on Cooperative Networking Challenges and Applications//, Vol. 30, No. 2, pp. 369-378, February 2012.
  - **Pan Li**, Chi Zhang, and Yuguang Fang, "{{tmc-dir11.pdf|The Capacity of Wireless Ad Hoc Networks Using Directional Antennas}}," //IEEE Transactions on Mobile Computing//, Vol. 10, No. 10, pp. 1374-1387, October 2011.
  - Hao Wen, Jia Liu, Chuang Lin, **Pan Li**, Yuguang Fang, and Fengyuan Ren, "{{tvt1103.pdf|A Storage-friendly Routing Scheme in Intermittently Connected Mobile Network}}," //IEEE Transactions on Vehicular Technology//, Vol. 60, No. 3, pp. 1138-1149, March 2011.
  - **Pan Li** and Yuguang Fang, "{{tmc0912.pdf|Impacts of Topology and Traffic Pattern on Capacity of Hybrid Wireless Networks}}," //IEEE Transactions on Mobile Computing//, Vol. 8, No. 12, pp. 1585-1595, December 2009.
  - **Pan Li**, Nicola Scalabrino, Yuguang Fang, Enrico Gregori, and Imrich Chlamtac, "{{tpds09.pdf|How to Effectively Use Multiple Channels in Wireless Mesh Networks}}," //IEEE Transactions on Parallel and Distributed Systems//, Vol. 20, No. 11, pp. 1641-1652, November 2009. (//Feature Article of the November Issue//)
  - Xiaoyan Zhu, **Pan Li**, Yuguang Fang, and Yumin Wang, "{{tvt0910.pdf|Throughput and Delay in Cooperative Wireless Networks With Partial Infrastructure}}," //IEEE Transactions on Vehicular Technology//, Vol. 58, No. 8, pp. 4620-4627, October 2009.
  - **Pan Li**, Chi Zhang and Yuguang Fang, "{{ton09.pdf|Asymptotic Connectivity in Wireless Ad Hoc Networks Using Directional Antenna}}," //IEEE/ACM Transactions on Networking//, Vol. 17, No. 4, pp. 1106-1117, August 2009. (We made some minor <html><a href="http://www.ece.msstate.edu/~li/doku.php?id=research:ton09"><span style="color:maroon">corrections</span></a></html> and here is the {{ton09-dir.pdf|corrected version}}.)
  - **Pan Li**, Hongqiang Zhai, and Yuguang Fang, "{{winet09.pdf|SDMAC: Selectively Directional MAC Protocol for Wireless Mobile Ad Hoc Networks}}," //ACM Wireless Networks//, Vol. 15, No. 6, pp. 805-820, August 2009.
  - Qiang Shen, Xuming Fang, Rongsheng Huang, **Pan Li**, and Yuguang Fang, "{{comcom09.pdf|Improving Throughput by Tuning Carrier Sensing in 802.11 Wireless Networks}}," //Computer Communications//, Vol. 32, No. 11, pp. 1263-1270, July 2009.
  - Qiang Shen, Xuming Fang, **Pan Li** and Yuguang Fang, "{{tvt09.pdf|Admission Control Based on Available Bandwidth Estimation for Wireless Mesh Networks}}," //IEEE Transactions on Vehicular Technology//, Vol. 58, No. 5, pp. 2519-2528, June 2009.
  - **Pan Li**, Qiang Shen, Yuguang Fang and Hailin Zhang, "{{twc094.pdf|Power Controlled Network Protocols for Multi-rate Ad Hoc Networks}}," //IEEE Transactions on Wireless Communications//, Vol.8, No.4, pp. 2142-2149, April 2009.
  - **Pan Li**, Chi Zhang and Yuguang Fang, "{{jsac09.pdf|Capacity and Delay of Hybrid Wireless Broadband Access Networks}}," //IEEE Journal on Selected Areas in Communications (JSAC) --- Special issue on Broadband Access Networks: Architectures and Protocols//, Vol. 27, No. 2, pp. 117-125, February 2009.
  - **Pan Li**, Xiaojun Geng and Yuguang Fang, "{{twc09.pdf|An Adaptive Power Controlled MAC Protocol for Wireless Ad Hoc Networks}}," //IEEE Transactions on Wireless Communications//, Vol. 8, No. 1, pp. 226-233, January 2009.
  - Jianfeng Wang, Hongqiang Zhai, **Pan Li**, Yuguang Fang and Dapeng Wu, "{{winet08.pdf|Directional Medium Access Control for Mobile Ad Hoc Networks}}," //ACM Wireless Networks//, February 12, 2008.
  - **Pan Li**, Xiaoxia Huang, Yuguang Fang, and Phone Lin, "{{tvt07.pdf|Optimal Placement of Gateways in Vehicular Networks}}," //IEEE Transactions on Vehicular Technology//, Vol. 56, No. 6, pp. 3421-3430, November 2007.





===== Magazine Articles =====
  - Haichuan Ding, Yuguang Fang, Xiaoxia Huang, Miao Pan, **Pan Li**, and Savo Glisic, "{{comst17.pdf|Cognitive Capacity Harvesting Networks: Architectural Evolution Towards Future Cognitive Radio Networks}}," //IEEE Communications Surveys and Tutorials//, Vol. 19, No. 3, pp. 1902-1923, 2017.
  - Sergio Salinas, Xuhui Chen, Jinlong Ji, and **Pan Li**, "A Tutorial on Secure Outsourcing of Large-scale Computations for Big Data," //IEEE Access//, 2016.
  - Changqing Luo, Laurence T. Yang, **Pan Li**, Xie Xia, and Han-Chieh Chao, "{{iwc0615.pdf|A Holistic Energy Optimization Framework for Cloud-assisted Mobile Computing}}," //IEEE Wireless Communications//, Vol. 22, No. 3, pp. 118-123, June 2015.




===== Books and Book Chapters =====
  - **Pan Li**, "Capacity of Wireless Ad Hoc Networks," //Encyclopedia of Wireless Networks//, Springer, 2018.
  - Xuanheng Li, Haichuan Ding, Yuguang Fang, Miao Pan, **Pan Li**, Xiaoxia Huang, Savo Glisic, "Collaborative Spectrum Trading and Sharing for Cognitive Radio Networks," //Handbook of Cognitive Radio//, Springer, 2017.
  - Miao Pan, Ming Li, **Pan Li**, and Yuguang Fang, "Spectrum Trading in Multi-Hop Cognitive Radio Networks," //Springer//, 2015.






