# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 17 May 2007 15:24:10 -0400
*               @admin      255
home	@ALL	1
photo	nicscal	1
research:*	test	1
pics:*	@ALL	0
pics:*	test	1
research:links	@	0
research:students	@ALL	1
teaching:ece4833	@ALL	1
teaching:ece4813	@ALL	1
research:*	@ALL	1
teaching:*	@ALL	1
*	@ALL	1
