<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: lipanleo
 * Date: Wed, 29 Apr 2009 15:26:59 -0500
 */

$conf['title'] = 'Pan Li\'s Home Page';
$conf['start'] = 'main';
$conf['template'] = 'sxs';
$conf['savedir'] = '/var/www/doku_data';
$conf['useacl'] = 1;
$conf['passcrypt'] = 'md5';
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'lipanleo@gmail.com';
$conf['spellchecker'] = 1;
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['plugin']['gallery']['lightbox'] = 1;

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content

