<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: lipanleo
 * Date: Sat, 19 May 2007 16:31:04 -0400
 */

$conf['title'] = '';
$conf['start'] = 'main';
$conf['template'] = 'sxs';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'lipanleo@gmail.com';
$conf['spellchecker'] = 1;
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['plugin']['gallery']['lightbox'] = 1;

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content

$conf['allowdebug'] = 0;
$conf['fetchsize'] = 0;
$conf['savedir'] = '/var/www/doku_data';
